---
- secret:
    name: SECRET_CONTAINER_IMAGE_INVENTORY_RECONCILER
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - CpFVHHI5FjJmrCOLKHL15gj1LbDd9GYHuz1bjlBMfpWLcur1/QPESN4MucC94RYp92BEG
          xEkbeImdghWTO+D6CgCRVAJskngAFjcEhB5fkY2LyRqVVsr1moW/lPees2l13bFNDB+GZ
          Uq9B8hz9QwdbVi5jCIRDm4/ip5CPeKZh12iaU9KQb/aaauPML5G98S5YpX6tRBx2tCHCQ
          9KbwwNbkGtVYeJIINwzhN2mtWYpVT1kE8RUuWTLJ7OPINZpYqnTk81qSj05fTcVnFnyNw
          muWibEJCHv3OwALy0+WPEkTgDDXBOitB1y4z9v/4/F37xfK2Ws33b4PPICQh+SUuM1iHY
          9lrSxt+8+vxFUeK+z9sX0mMucVlquP08I8CvSYcpn5jagITrwij9u8iokRj4mqd0X8kr7
          ecLetUT9tpoySwXAAjJ4aQBAazv6jeLnPGALL2/QvhsdaKNBjxjO4o+4oIaevJMGWS0e8
          l8AvFjNRhx2/yoK6seVV+0PzYC7iJB3xItVq5AiKQHNaLBUMqPUmrx962X4rrrMzxzpTR
          u/O3O2igLBHhIR7qaa6gMwH+6v2Fl40kt1n9ieS0q++Xr+TMqToGOpfSG1JD3aXRiF04e
          9WCYgkdetANrH1N027QN0Af06gMv3/o4SU8f358ACPpyX9o3hth61pLOw+8N7A=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - euk+LNTOxUJRTUPKhyHW8CKvgl1WtWN4PcVMMz5M9jYzA+0XIIj8ZhmcMHJvxvFXNsPso
          +QJrWlkHE8xVQUihRxpC33dqHM1DSgI0ynViXB+zAsXZFfzd5t4DmrhfxtDBdZigSO2Vy
          HrPlRn+NoPlINQ8cbCFnPBnZsV8lAKPdcOjXfIhL7nfN3D9ztuwUGtC02Pm8Fct4X2U8Q
          /siQ6oRhXqbD7ARwhXGlSDObxgcv3ffOuJsmG57u/TQX888JsQTtLEFHLzMJwKizAXciU
          70FLHIgRonW/FczbhcZKKA6sOufripJg5KDPuWr01letkVZm8za/6NLIPlUCrg12HHhXW
          lhXeu71JGMVGaWaZssxMTuIfC2Dbb5ia9jjw0xXhYw6WpJ2JmlSPiSIbX1IUsGpFNUwhL
          YNjvCEuPO6TWOVw3TwhzNVkms0h8oTsgYqY9i8vOnrhBjCq8IM48c+1cNyAiYp3gkdU8r
          hv7F+5fg+Y+0DmdKUbuyQiEQeY3Unf8hzjrlqw/kGnirQkMbADn7rCP3VdVvEA2C9Mdk8
          jIYYTc2qQelrZHFi4Dpl24vd3c58YegPYW7Ut1YI2wuoCWZLFKwgZBewCfWNAj613QSXt
          gD6IJeVQSZbaRk9K1VSdb4gaAUwV/uxiQUQmeQ2YkwYQHW+q59LjQQuWJmyiNM=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - BBCZnp6TKP0u6cqQ/QMrJufpsRAHWhxMlQx41S0SDYzTvsmkts36aieDZ5l/3Ka4nBvu7
          cTdxoL5j3/jMf5X+0y2STc110nX9bdMDEhY7Oeop1Du4PEy+wn8ltvfeK0ypxU+irB/lI
          zbCngCc1uk2L4EbW1iCD0kO+ISFKleeontdF3q0/1voU0usRCwmFEwU+VWNG6YhWIysBF
          0vMUp0yBKoM6oPEM47R9AJxZYi916+C+zrg+FH8SbZnUp6CKL2B9tCT5syymyydtzl6hZ
          RrT5i582pl41hA0MCjvWTVzDAhYTqRJRujOF320Lmj7ltMTEl3rrzj/OPU2Ma/OtLdbM2
          IBNYJxfB/XCThJ4+W5cOAPrW7UI3q08sCtKY2q+Kuba/Pltf5hySl4kMfUx/8B5XQXxnT
          v86T4G4PQvxv0R5pty5iHGuStDhTmZZ7zpJvSIZFgExuruUlP54dfPhrIyIx7ANjenl5c
          wn+L1OPmFDmdNqL9Z11D2klL0eSPQDG9W6AuK+mAXc98PA/7que6xWrnCn2/j4P81JvcL
          JUmo4VKBikYhfKlI+kCyFu++XyA++Kcmk9kw+fEw2o1bkUVCoOwfIa7oIr/RCxii77xIY
          ShGcqTZGLbkHqjUHHtrVfudwl7TRWgvGAs4JF8k/OgmR4x/QmSQR5kHgAADJBU=

- semaphore:
    name: semaphore-container-image-inventory-reconciler-push
    max: 1

- job:
    name: container-image-inventory-reconciler-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-container-image-inventory-reconciler-push
    abstract: true
    semaphores:
      - name: semaphore-container-image-inventory-reconciler-push
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true
      push_sbom: true

- job:
    name: container-image-inventory-reconciler-push
    parent: abstract-container-image-inventory-reconciler-push
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_INVENTORY_RECONCILER
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
        - container-image-inventory-reconciler-build
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
    periodic-midnight:
      jobs:
        - container-image-inventory-reconciler-push
    post:
      jobs:
        - container-image-inventory-reconciler-push:
            branches: main
    tag:
      jobs:
        - container-image-inventory-reconciler-push
