---
- secret:
    name: SECRET_CONTAINER_IMAGE_INVENTORY_RECONCILER
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - S/XnQ9mIZ+HPuT1Bgxq+eK05D0olb+/o1XOrWVo8NUnu5m39g/EDTstSoXS02mUhKZWQQ
          VnGjlvaJ+KdXv3M0j+byrHSgfCtP65DeafNS0olDJne5TXJiJckFt+XTUent1mbwK+dwD
          pt6l+d8+G1DfesiINR0s5Yw2V9cTvEd2LCoNPMggG0ZmtDBn3tLCmyFYZqVQPoGXc2QIS
          XqcWUX6YXG7yXnKWySrxa3dp0MF5zbGJaIyzCJGrehQV3t0PigkhgytHeFkXvKCTVJrTN
          z+wgrxu87yXmmuTmK2b3wEE0f9/Xob/2SZ9ns2hn+ENrUkZRJ7a9uCBU+qc90saoe5iDU
          WjSiveLCTNGo1La0t5gGVJNogN7TtWUUPLnR1YApoNhCM4K9SU7M+Ztgnu/b2c3EvtJ1i
          VA6TfKNp8cDfMadCgzXbgSNtSn4stVlj6207sLqLxTM+0dOzSdkfuMlqBMcDrBVilnam+
          CLKj/rQpSUv/ceD+Z5YynO/3Ycc7uFsAzzgJJkG9L0rZ5Vfw6UQm/Xr3QDsfddtHtxE88
          n5Ri/NF0/rmn3e+LRjOOloMzTFefs0UDPOyxEIS6RAel4KpHy+69HstaDhv2fgwWjfjGY
          XYECN2C+3hB0fV3ybkngPJPnhzdPvcx1rYh14DJC5GZGnXUne4bI1O5vvAX4OQ=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - YQblJoSWPI4o/gMHlknh7LG/f3fjdsY170NGw3+g2Vl3yYOlJOpRpmirTRwvLoqBxwhFB
          9/HcJtLLkiiC25JZIKDjWknkJrpip2EQujfkLc2NKVqmtJ+0DzKB3xGGZ0GoF3sGkG1P0
          KTfY7BB1+SkKFfQvtTl7qVU4PVCqP3xxjPFF/ODE+eL7d76Yx9vaeblfWfwYDDrMJmavq
          bFzB/fn5RYu7v9W8vsSzZpq/l3zgEyP7mRIXo03Wsg81lYHsvwtJGbKt9bpRjtkMzH568
          OLKxqk+N34IrY/qfIXObaU+NKOAvgnXxMCBtmm21ehnZ+UIT1li6sUobdRMaSBz0qzz3t
          6eY+6PaQ64ygd+TU/lL+9QW/azX7dn1ncJxUQJ0/PGyAIizNZes4TfDg7+0FI0vSyBFG1
          hmeh69rWafb+P5vWNN3s+H7Md2pPow1NJ5tzFsVpDAfFFYLOJxgLtV62PaHomRSSnnCX7
          9ht/UwNWfmdRHEkZ6jEj0MfY/tIXbdj0q0P5oqpxrrkY+fCMjTSVMMD8TydPYLu3Dr//T
          217NcYEHKZgfiCqA/a3lWUj/inmZEQOXjAPNQL6+kmivxNCeSsth5t4O1TANFQ0tSvPa1
          JULhffXGv+1o0dpg+94VTjVVRhdMoeT58/xsYvqBmEMJ/AelorpD1v9GsBiIdM=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - dyFUnprEWJp4fgaO5ICTOISdy0ryP56b1vIimpbmIwmICHyCN3LweDbxSsHycV69iLYfW
          lndr1aq+XrMW35VyRem2wypf5wxUzhVmQkAxb+of9Vke0Aj36htWweYKZRs/7Rn8+x2jZ
          yHaadtg+CmnUPmbIpSKbzWsRqn/JahIJ4L3JJh/0GBHfRtix1JYuXu+QW77dgH7010KES
          fd93NrcKDTwjq+7ZPkIIiPY0mis5yY+IusOSQlUDu6Qo9IE5PmGlqOtob2wL8+Soh38Fb
          +M0p8MvmV4yy73iQqLv42XMZsp20QaYmOErOM0ntEj0N6/RwiSQSe/wBOwm8mpxNPX7sO
          WEGMANQJSj/pIp6XOA/amSCRfoZZJ3OVmeZkggr5INhkTA4IDNxQwbAxx3t5Fner3BS1W
          2iVwucnJbVThtx+Rqt4SfsVvTvOQzMgTNrLcPhu+xCycq2ledp1u7IbRvD92L8DUXQXg3
          wQqFRF0DZrqbfAV8brmpJQJcX/lysn3FUHGh1ZwrU6LC/SBNoSbOMV/QCwD/zl6EkIR24
          ioE0dzOvbvKJ7k6JdNwSEA5U7kvPWWNlIopCrtJFlxMG1puwMVasYGWTLF1CRCH4csgam
          NKLV1CDCvsAJl17W35e0JAGyk1S9LpILAuarA/7cDnxXIngSN3XZsXzgVjqsxY=

- semaphore:
    name: semaphore-container-image-inventory-reconciler-push
    max: 1

- job:
    name: container-image-inventory-reconciler-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-container-image-inventory-reconciler-push
    abstract: true
    semaphores:
      - name: semaphore-container-image-inventory-reconciler-push
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true
      push_sbom: true

- job:
    name: container-image-inventory-reconciler-push
    parent: abstract-container-image-inventory-reconciler-push
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGE_INVENTORY_RECONCILER
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
        - container-image-inventory-reconciler-build
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - yamllint
    periodic-midnight:
      jobs:
        - container-image-inventory-reconciler-push
    post:
      jobs:
        - container-image-inventory-reconciler-push:
            branches: main
    tag:
      jobs:
        - container-image-inventory-reconciler-push
